# == APPLICATION ==
spring.application.name=bloodyglyph-backend
spring.config.import=optional:file:./env.properties
server.port=${PORT:7001}
# == DATABASE CONFIGURATION ==
spring.datasource.url=${DB_URL}
spring.datasource.username=${PG_USERNAME}
spring.datasource.password=${PG_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
# == JPA / HIBERNATE ==
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false
# ==================== JWT CONFIGURATION ====================
jwt.secret=${JWT_SECRET}
jwt.expirationms=${JWT_EXPIRATION_MS}
#==================== SWAGGER ====================
#link da usare : http://localhost:7001/swagger-ui/index.html
#==================== CLOUDINARY ====================
cloudinary.name=${CLOUDINARY_CLOUD_NAME}
cloudinary.apikey=${CLOUDINARY_API_KEY}
cloudinary.apisecret=${CLOUDINARY_API_SECRET}
#==================== MAILGUN ====================
mailgun.domain=${MAILGUN_DOMAIN}
mailgun.api-key=${MAILGUN_API_KEY}
mailgun.from=${MAILGUN_FROM}
mailgun.banner-url=${MAILGUN_BANNER_URL}